import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthSession from './session'
import Nav from './components/nav'
// import { authOptions } from './api/auth/[...nextauth]/route'
// import { getServerSession } from "next-auth"


const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.ico"
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
        <Nav/>
        {children}
        </AuthSession>
        </body>
    </html>
  )
}
// 전체를 읽는 곳 메인